#ifndef FILE_EDITOR_CONFIG_H
#define FILE_EDITOR_CONFIG_H

#include <Windows.h>

#define FILE_EDITOR_DEFAULT_CLASS_NAME L"Edit"
#define FILE_EDITOR_DEFAULT_STYLE      WS_CHILD | WS_VISIBLE | WS_BORDER | ES_LEFT | ES_MULTILINE | ES_AUTOVSCROLL | ES_AUTOHSCROLL

#endif // FILE_EDITOR_CONFIG_H