#ifndef MAIN_WINDOW_CONFIG_H
#define MAIN_WINDOW_CONFIG_H

#include <Windows.h>

// TODO: Add ability to change
#define MAIN_WINDOW_DEFAULT_CLASS_NAME L"MainWindowClass"
#define MAIN_WINDOW_DEFAULT_ICON       IDI_APPLICATION
#define MAIN_WINDOW_DEFAULT_CURSOR     IDC_ARROW
#define MAIN_WINDOW_DEFAULT_BACKGROUND (HBRUSH)(COLOR_WINDOW + 1)
#define MAIN_WINDOW_DEFAULT_TITLE      L"Adly"

#define MAIN_WINDOW_DEFAULT_EX_STYLE 0
#define MAIN_WINDOW_DEFAULT_STYLE    WS_OVERLAPPEDWINDOW
#define MAIN_WINDOW_DEFAULT_X        CW_USEDEFAULT
#define MAIN_WINDOW_DEFAULT_Y        CW_USEDEFAULT
#define MAIN_WINDOW_DEFAULT_WIDTH    CW_USEDEFAULT
#define MAIN_WINDOW_DEFAULT_HEIGHT   CW_USEDEFAULT

LRESULT CALLBACK main_window_proc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam);

#endif // MAIN_WINDOW_CONFIG_H