#ifndef MENU_ELEMENT_CONFIG_H
#define MENU_ELEMENT_CONFIG_H

#include <Windows.h>

#define MENU_ELEMENT_OPTION_FLAGS    MF_STRING
#define MENU_ELEMENT_SEPARATOR_FLAGS MF_SEPARATOR

#endif // MENU_ELEMENT_CONFIG_H